# NOTE
#   This cannot be a reusable workflow, as trusted publishing requires
#   "permissions: id-token: write" and this is forbidden for
#   reusable workfows.
#   This workflow is therefore generally not used. Instead, we use
#   publish_on_release which contains the same steps, but is triggered
#   by a release.

name: Publish to PyPI
on:
  workflow_dispatch:
    inputs:
      checkout:
        description: 'Commit / Branch / Tag / SHA to checkout'
        required: false
        default: ''
        type: string

jobs:
  publish-pypi:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5

      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkout }}

      - name: Install dependencies for building package
        run: python -m pip install --upgrade pip build

      - name: Install distribution 📦
        run: python -m pip install .

      - name: Build distribution 📦
        run: python -m build

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
