name: Unit tests
on:
  workflow_dispatch:
    inputs:
      checkout:
        description: 'Commit / Branch / Tag / SHA to checkout'
        required: false
        default: ''
      tag:
        description: 'Tag to apply'
        required: false
        default: ''
      python-version:
        description: 'Python version'
        required: false
        default: '3.8'
  workflow_call:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]'
      - 'v?[0-9]+.[0-9]+.[0-9]+rc[0-9]*'
      - 'v?[0-9]+.[0-9]+.[0-9]+a[0-9]*'
      - 'v?[0-9]+.[0-9]+.[0-9]+b[0-9]*'
      - 'v?[0-9]+.[0-9]+.[0-9].post[0-9]*'
      - 'v?[0-9]+.[0-9]+.[0-9].dev[0-9]*'
      - 'v?[0-9]+.[0-9]+.[0-9].post[0-9]*.dev[0-9]*'

jobs:
  run-tests:
    uses: ./.github/workflows/run_tests.yml
    with:
      checkout: ${{ inputs.checkout }}

  release-pypi:
    steps:
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkout }}

      - name: Assign tag ${{ inputs.tag }}
        if: ${{ inputs.tag }}
        run: |
          git tag ${{ inputs.tag }}
          git push --tags

      - name: Install dependencies for building package
        run: python -m pip install --upgrade pip build

      - name: Install distribution 📦
        run: python -m pip install .

      - name: Build distribution 📦
        run: python -m build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
